### ISSUE TITLE
Don't execution in node env after deno project bundling result

### ISSUE THREAD

**Issue by gseok** [denoland/deno_std#1704]
- Deno default logger's code using `Top Level await'
  - https://deno.land/std@0.117.0/log/mod.ts#L211

And...

- Deno default bundler don't support `target` or `module` config
  - https://deno.land/manual@v1.16.4/typescript/configuration#how-deno-uses-a-configuration-file

So

If using `Deno default loger(std lib)` And Bundling code's result include follow codes
```
...

await setup(DEFAULT_CONFIG);

...
```
These code don't execution in node env.... because node(in my test v17.2.0) is not support top level await.

- Can not you change it? `https://deno.land/std@0.117.0/log/mod.ts#L211`
```
(async () => {
  await setup(DEFAULT_CONFIG);
})();
```

**Comment by kt3k** [comment]
Node.js should support top level await in ESM mode. Do you still see an error if you change the file extension of the script to `.mjs`?

**Comment by gseok** [comment]
> Node.js should support top level await in ESM mode. Do you still see an error if you change the file extension of the script to `.mjs`?

- There are no `top level await error` when change output file name `js` to `mjs`
  - `deno bundle -c ./deno.json ./src/sever.ts ./dist/server.mjs`  
- But... follow new error displayed...

```
class DenoStdInternalError extends Error {
                                   ^

ReferenceError: Cannot access 'Error' before initialization
```

**Comment by kt3k** [comment]
> Is it same issue(before initialization)? - denoland/deno#12086 (comment)

Ah, looks like so to me. Can you check with the canary version of Deno (You can upgrade to canary with `deno upgrade --canary` command. BTW we're going to release the next version 1.17 on 16th Dec)

**Comment by gseok** [comment]
`canary` version test
```
deno 1.16.4+c9d32e0 (canary, x86_64-apple-darwin)
v8 9.7.106.15
typescript 4.5.2
```

-  `node ./dist/server.mjs`  don't running....
```
class LineStream extends TransformStream {
                         ^

ReferenceError: TransformStream is not defined
```

- `deno run --allow-run --allow-net --allow-read --unstable ./dist/server.mjs` SUCCESS!

There is a still some problems at bundled `mjs` file to run in node

**Comment by kt3k** [comment]
The module (`std/streams/delimiter`) seems depending on global [TransformStream](https://developer.mozilla.org/en-US/docs/Web/API/TransformStream) class, which is a part of Web Stream API. Deno provides Web Stream in global namespace, but Node.js doesn't. That seems the reason of the above difference in both runtimes.

Can you try to add a polyfill of Web Stream API (for example, `import "https://unpkg.com/web-streams-polyfill/dist/polyfill.min.js";`) at the beginning of your server's entrypoint? I think that should solve the above ReferecneError issue

**Comment by gseok** [comment]
`import "https://unpkg.com/web-streams-polyfill/dist/polyfill.min.js";` then pass `TransformStream` error !!

But... still don't running in node... follow error

```
        getRandomValues: crypto.getRandomValues?.bind(crypto),
                                ^

TypeError: Cannot read properties of undefined (reading 'getRandomValues')
```

I think, It looks like a similar problem. `Deno` and `Node` diff api..
- deno: https://deno.land/std@0.117.0/crypto
- node: https://nodejs.org/api/crypto.html
  - node not have `getRandomValues`

---

ps. There is an additional questions...
- in my codes... There are no using the crypto api but `server.mjs` include crypto code after bundling.
  - in my codes... NOT import deno std crypto...and NOT using crypto api.
```
...
const digestAlgorithms = [
    "BLAKE2B-256",
    "BLAKE2B-384",
    "BLAKE2B",
    "BLAKE2S",
    "BLAKE3",
    "KECCAK-224",
    "KECCAK-256",
    "KECCAK-384",
    "KECCAK-512",
    "SHA-384",
    "SHA3-224",
    "SHA3-256",
    "SHA3-384",
    "SHA3-512",
    "SHAKE128",
    "SHAKE256",
    "RIPEMD-160",
    "SHA-224",
    "SHA-256",
    "SHA-512",
    "MD5",
    "SHA-1", 
];
const webCrypto = ((crypto)=>({
        getRandomValues: crypto.getRandomValues?.bind(crypto),
        randomUUID: crypto.randomUUID?.bind(crypto),
        subtle: {
            decrypt: crypto.subtle?.decrypt?.bind(crypto.subtle),
            deriveBits: crypto.subtle?.deriveBits?.bind(crypto.subtle),
            deriveKey: crypto.subtle?.deriveKey?.bind(crypto.subtle),
            digest: crypto.subtle?.digest?.bind(crypto.subtle),
            encrypt: crypto.subtle?.encrypt?.bind(crypto.subtle),
            exportKey: crypto.subtle?.exportKey?.bind(crypto.subtle),
            generateKey: crypto.subtle?.generateKey?.bind(crypto.subtle),
            importKey: crypto.subtle?.importKey?.bind(crypto.subtle),
            sign: crypto.subtle?.sign?.bind(crypto.subtle),
            unwrapKey: crypto.subtle?.unwrapKey?.bind(crypto.subtle),
            verify: crypto.subtle?.verify?.bind(crypto.subtle),
            wrapKey: crypto.subtle?.wrapKey?.bind(crypto.subtle)
        }
    })
)(globalThis.crypto);
...
```

**Comment by kt3k** [comment]
Can you share the dependencies of your server? What's the result of `deno info -c ./deno.json src/server.ts`?

**Comment by cs09g** [comment]
I found `oak` uses `ws` and `ws` uses `crypto`. So, the result of `deno bundle` contains crypto?

```
...
[0m[38;5;8m│ ├─┬[0m https://deno.land/x/oak@v9.0.1/helpers.ts[0m[38;5;8m (1.56KB)[0m
[0m[38;5;8m│ │ ├─┬[0m https://deno.land/x/oak@v9.0.1/context.ts[0m[38;5;8m (7.72KB)[0m
[0m[38;5;8m│ │ │ ├─┬[0m https://deno.land/x/oak@v9.0.1/application.ts[0m[38;5;8m (21.85KB)[0m
[0m[38;5;8m│ │ │ │ ├──[0m [0m[38;5;8mhttps://deno.land/x/oak@v9.0.1/context.ts[0m[0m[38;5;8m *[0m
[0m[38;5;8m│ │ │ │ ├─┬[0m https://deno.land/x/oak@v9.0.1/deps.ts[0m[38;5;8m (1.74KB)[0m
...
[0m[38;5;8m│ │ │ │ │ ├─┬[0m https://deno.land/std@0.105.0/ws/mod.ts[0m[38;5;8m (14.55KB)[0m
[0m[38;5;8m│ │ │ │ │ │ ├──[0m [0m[38;5;8mhttps://deno.land/std@0.105.0/_util/assert.ts[0m[0m[38;5;8m *[0m
[0m[38;5;8m│ │ │ │ │ │ ├──[0m https://deno.land/std@0.105.0/_util/has_own_property.ts[0m[38;5;8m (950B)[0m
[0m[38;5;8m│ │ │ │ │ │ ├──[0m [0m[38;5;8mhttps://deno.land/std@0.105.0/async/deferred.ts[0m[0m[38;5;8m *[0m
[0m[38;5;8m│ │ │ │ │ │ ├──[0m [0m[38;5;8mhttps://deno.land/std@0.105.0/bytes/mod.ts[0m[0m[38;5;8m *[0m
[0m[38;5;8m│ │ │ │ │ │ ├─┬[0m https://deno.land/std@0.105.0/crypto/mod.ts[0m[38;5;8m (8.99KB)[0m
[0m[38;5;8m│ │ │ │ │ │ │ └─┬[0m https://deno.land/std@0.105.0/_wasm_crypto/mod.ts[0m[38;5;8m (1.02KB)[0m
[0m[38;5;8m│ │ │ │ │ │ │   └─┬[0m https://deno.land/std@0.105.0/_wasm_crypto/crypto.js[0m[38;5;8m (11.6KB)[0m
[0m[38;5;8m│ │ │ │ │ │ │     └─┬[0m https://deno.land/std@0.105.0/_wasm_crypto/crypto.wasm.js[0m[38;5;8m (194.26KB)[0m
[0m[38;5;8m│ │ │ │ │ │ │       └──[0m [0m[38;5;8mhttps://deno.land/std@0.105.0/encoding/base64.ts[0m[0m[38;5;8m *[0m
...
```

**Comment by kt3k** [comment]
> I found oak uses ws and ws uses crypto. So, the result of deno bundle contains crypto?

Sounds so to me. And oak recently dropped the dependency of ws. I think upgrading oak to the latest might solve the issue.

**Comment by gseok** [comment]
@cs09g is my team member.  we guess... our project `crypto` is include by `oak`

**Comment by gseok** [comment]
- deno bundle result running in `node` is possible (theoretically)
- But, use the third-party library(e.g oak), not a standard LIB(stdlib), the more separate actions(e.g. add polyfill) is needed.
- Or waiting the third-party lib's own fixed....

so we decided `deno bundle` result do not execute by 'node'. we execute by 'deno'.
 - we think it is make sense.. because project already 'deno' project..

@kt3k thank you for your help~!
